version: '3.8'

services:
  db:
    image: postgres:13
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: face_detect_db
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build:
      context: .
    env_file:
      - .env
    container_name: face_detect_app
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: bash -c "uvicorn app.main:app --host 0.0.0.0 --port 8000"

volumes:
  postgres-data:
